### ISSUE TITLE
Heroku app not working the same as Gitpod (not masking the word)

### ISSUE THREAD

**Issue by SerjiVutinss** [gmit-sweng-20/ca2-sinatra-saas-SerjiVutinss#3]
While running in Gitpod, the app runs as expected and fully masks the word until correct guesses have been made.  When deployed on Heroku, however, the entire word is displayed unmasked.

I cannot seem to figure out the difference and would appreciate any advice, thanks.

**Comment by john-french** [comment]
Kudos for bringing it to my attention like this rather than an email, feels like being a working developer again!
I'll check it out, thanks for pointing it out.

**Comment by john-french** [comment]
any joy with this @SerjiVutinss?

**Comment by SerjiVutinss** [comment]
> any joy with this @SerjiVutinss? i didn't spot anything.

No luck.  Cucumber is passing all the test but Gradescope is failing them, which is to be expected I guess...

I might try again from the start on a new branch and see if anything differs.

**Comment by john-french** [comment]
Just out of curiosity, maybe try running your app on GitPod and submitting the gitpod URL of the app to Gradescope.

**Comment by SerjiVutinss** [comment]
@john-french Thanks for taking the time to look at this, turns out it was a simple, hard to spot error in my code.

Resolved in commit: https://github.com/gmit-sweng-20/ca2-sinatra-saas-SerjiVutinss/commit/87e8fa23e1cdbffb66ba899dae337bf4bf38c22a
